[build]
  base = "exampleSite/"
  command = "mv ../{repo,rusty-typewriter} && cd exampleSite && hugo --gc --minify --baseURL $BASE_URL && mv ../../{rusty-typewriter,repo}"
  publish = "exampleSite/public"

[context.production]
  environment = { 
    HUGO_VERSION = "v0.122.0", BASE_URL = "https://rusty-typewriter.netlify.app"
  }

