[build.environment]
  BASE_URL = "https://rusty-typewriter.netlify.app/demo"
  BASE_PATH = "demo"
  HUGO_VERSION = "v0.122.0"
  NODE_VERSION = "22"
  TZ = "America/Sao_Paulo"

[build]
  base = "exampleSite/"
  publish = "public"
  command = """\
    mv ../../{repo,rusty-typewriter} && \
    hugo --gc --minify --baseURL $BASE_URL && \
    mkdir tmp && \
    mv public/* tmp && \
    mv tmp $BASE_PATH && \
    (mv public/$BASE_PATH/404.html public || true) && \
    mv ../../{rusty-typewriter,repo}
  """

